// Builds tools/voice_manifest.json — every voiced line in the game with a stable id.
// Run: node game/tools/build_voice_manifest.js
// The Python generator consumes this; the game computes the same ids at runtime (src/core/voice.js).

const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const { Quests } = require(path.join(root, 'src/world/quests.js'));
const { Companions } = require(path.join(root, 'src/world/companions.js'));
const { createPitCombat } = require(path.join(root, 'src/combat/pit.js'));
const { VoiceMan } = require(path.join(root, 'src/core/voice.js'));

const lines = [];
const seen = new Set();
function add(speaker, text, note) {
  if (!text || text.includes('{N}')) return; // nickname-templated lines can't be pre-recorded
  speaker = speaker.toUpperCase();
  const id = VoiceMan.hash(speaker + '|' + text);
  if (seen.has(id)) return; seen.add(id);
  lines.push({ id, speaker, text, note: note || '' });
}

// ---- Bellow: fight taunts ----
const combat = createPitCombat({ width: 100, height: 100, ui: {} });
for (const f of combat.FIGHTS) add('BELLOW', f.taunt.replace(/^"|"$/g, ''), 'board taunt: ' + f.name);

// ---- character intro bios (Narrator) ----
const pitSrc = fs.readFileSync(path.join(root, 'src/combat/pit.js'), 'utf8');
const bios = pitSrc.match(/const BIOS=\{[\s\S]*?\};/);
if (bios) for (const m of bios[0].matchAll(/\w+:'((?:[^'\\]|\\.)*)'/g))
  add('NARRATOR', m[1].replace(/\\'/g, "'"), 'character intro bio');
// death quotes (Narrator)
const dq = pitSrc.match(/const q=\[([\s\S]*?)\];/);
if (dq) for (const m of dq[1].matchAll(/'((?:[^'\\]|\\.)*)'/g))
  add('NARRATOR', m[1].replace(/\\'/g, "'"), 'death quote');

// ---- main quest dialogs ----
const I = Quests.innkeeper;
for (const k of ['rumorFree', 'rumorPaidOffer', 'rumorPaid', 'broke', 'done']) add('MARLOW', I[k], 'innkeeper');
const C = Quests.cult;
add('NARRATOR', C.campSign, 'camp'); add('NARRATOR', C.caravanSign, 'caravan');
add('THE QUARRY BOY', C.captive.freed, 'beat 3');
add('SHEN SAMA', C.shenSama.text, 'beat 3 cameo');
add('THE VEILED WOMAN', C.buyer.text1, 'beat 4'); add('THE VEILED WOMAN', C.buyer.text2, 'beat 4');
add('NARRATOR', C.buyer.choiceKeep, 'beat 4'); add('NARRATOR', C.buyer.choiceGive, 'beat 4');
for (const k of ['text1', 'text2', 'text3']) add('ANKUNYX', C.finale[k], 'finale');
for (const k of ['text1', 'text2', 'text3']) add('NARRATOR', C.finaleRonin[k], 'ronin finale');

// ---- Varenholm arc ----
const V = Quests.varenholm;
add('NARRATOR', V.coach, 'varenholm'); add('NARRATOR', V.performance1, 'varenholm');
add('NARRATOR', V.performance2, 'varenholm'); add('NARRATOR', V.performance2druid, 'varenholm druid');
add('NARRATOR', V.done, 'varenholm');
const K = V.cookie;
for (const k of ['greet', 'greetDruid', 'jobBrief', 'afterJob', 'afterCult', 'afterCultDruid']) add('COOKIE', K[k], 'cookie');

// ---- druid heritage variants (appended strings hash differently — record the combos) ----
const D = Quests.druid;
add('MARLOW', I.rumorPaid + D.marlowBeat, 'druid variant');
add('SHEN SAMA', C.shenSama.text + D.shenSamaAdd, 'druid variant');
add('THE VEILED WOMAN', C.buyer.text1 + D.vialHum, 'druid variant');
add('ANKUNYX', C.finale.text2 + ' ' + D.finaleGaze, 'druid variant');
add('NARRATOR', D.captureSign, 'druid capture'); add('NARRATOR', D.captureAfter, 'druid capture');

// ---- companions ----
for (const [key, c] of Object.entries(Companions)) {
  add(c.name, c.greet, 'greet');
  for (const line of c.chat) add(c.name, line, 'chat');
  for (const k of ['recruitAsk', 'recruitYes', 'recruitNo', 'recruitVial', 'recruitBrew'])
    if (c[k]) add(c.name, c[k], 'recruit');
}

const out = path.join(__dirname, 'voice_manifest.json');
const chars = lines.reduce((n, l) => n + l.text.length, 0);
fs.writeFileSync(out, JSON.stringify({
  _readme: 'Generated by build_voice_manifest.js. Feed to generate_voices.py.',
  speakerSlots: {
    // game speaker -> tts_config.json character_voices slot
    'NARRATOR': 'Narrator', 'BELLOW': 'Bellow', 'MARLOW': 'Innkeeper',
    'ANKUNYX': 'Kenji', 'SHEN SAMA': 'Shen Sama',
    'THE QUARRY BOY': 'Quarry Boy', 'THE VEILED WOMAN': 'Veiled Woman',
    'BRAKKA': 'Brakka', 'VEXA': 'Vexa', 'DORIAN': 'Dorian',
    'FAELAR': 'Faelar', 'SYLVARA': 'Sylvara', 'PIPPA': 'Pippa',
    'COOKIE': 'Cookie', 'VERDANCE': 'Narrator', 'THE CAPTURE TEAM': 'Narrator',
    'THE PERFORMANCE': 'Narrator', 'THE COACH ROAD': 'Narrator', 'THE ROAD SOUTH': 'Narrator',
  },
  voiceHints: {
    'Bellow': 'booming gravel-voiced arena announcer, theatrical, middle-aged man',
    'Quarry Boy': 'young man, shaken but defiant, rural accent',
    'Veiled Woman': 'woman 30s, desperate dignity, voice cracks under control',
    'Brakka': 'deep gruff orc mercenary, terse, dry',
    'Vexa': 'young woman, fast manic gleeful energy, smirking',
    'Dorian': 'earnest formal knight, warm baritone, self-deprecating',
    'Faelar': 'serene elf, unhurried, dry wit, ageless',
    'Sylvara': 'cold precise aristocratic woman, cutting consonants',
    'Pippa': 'bright halfling woman, relentlessly cheerful, quick',
  },
  count: lines.length, totalChars: chars, lines,
}, null, 2));
console.log(`voice_manifest.json: ${lines.length} lines, ${chars} chars (~$${(chars * 0.00015).toFixed(2)}-$${(chars * 0.0003).toFixed(2)} ElevenLabs)`);
