// gen_wiki.js — regenerates the auto wiki under docs/knowledge base/wiki/ from the
// actual game source (quests.js, companions.js, citymap.js, and the combat sim's
// FIGHTS roster). Re-run after ANY content change so the wiki never drifts:
//
//   node game/tools/gen_wiki.js
//
// Files emitted: quests.md, characters.md, monsters.md, locations.md, README.md.
// The MONSTER_BEHAVIOR table below is curated (behaviors live in code logic, not
// data) — update it by hand if you add/retune an enemy type. Everything else is
// pulled live from source, so it self-updates.

const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');                       // game/
const OUT = path.join(root, '..', 'docs', 'knowledge base', 'wiki');
fs.mkdirSync(OUT, { recursive: true });

const { Quests } = require(path.join(root, 'src/world/quests.js'));
const { Companions } = require(path.join(root, 'src/world/companions.js'));
let CityMap = {}; try { CityMap = require(path.join(root, 'src/world/citymap.js')).CityMap; } catch (e) {}

// FIGHTS roster from the live combat sim (headless instance)
let FIGHTS = [];
try {
  global.window = global; global.document = undefined;
  const { createPitCombat } = require(path.join(root, 'src/combat/pit.js'));
  FIGHTS = createPitCombat({ width: 1280, height: 720, ui: {} }).FIGHTS || [];
} catch (e) { console.log('note: could not load FIGHTS roster (' + e.message + ')'); }

const esc = s => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const stamp = new Date().toISOString().slice(0, 10);
const head = (title) => `# ${title}\n\n> AUTO-GENERATED by \`game/tools/gen_wiki.js\` on ${stamp}. Do not hand-edit — re-run the generator after source changes.\n\n`;
const write = (file, body) => { fs.writeFileSync(path.join(OUT, file), body); console.log('  wrote wiki/' + file); };

/* ---------------- QUESTS ---------------- */
(function () {
  let md = head('Quests');
  md += `The game has THREE main-quest tracks, chosen by character. Side content (guild hunts, companions, duels) is shared or character-gated.\n\n`;

  md += `## Main quest — The Ankuspawn Conspiracy (Ronin, Druid, Warlock)\n\nDriven by flags \`q-<id>\`; states: (unset) → \`active\` → \`done\`. Order:\n\n`;
  md += `| # | id | Title | Objective | Text |\n|---|---|---|---|---|\n`;
  for (const q of Quests.main) md += `| ${q.id.match(/mq(\d)/) ? q.id.match(/mq(\d)/)[1] : ''} | \`${q.id}\` | ${esc(q.title)} | ${esc(q.objective)} | ${esc(q.text).slice(0, 160)} |\n`;
  md += `\n**Endings:** Ronin = the Emperor never comes (empty-road epilogue, \`cult.finaleRonin\`). Druid = Emperor scene + secret Varenholm coach (\`mq6-the-dancer\`). Warlock = Emperor scene, then the White-Writ epilogue (see below).\n\n`;

  if (Quests.warlockEpilogue) {
    md += `## Warlock epilogue — the White Writ → Lady Nyx\n\nFlags \`q-wq1\`..\`q-wq3\`. After the plaza finale a White-Writ ambush replaces the credits; survive it → the Pale Courier → the black carriage to the Ashenveil → Lady Nyx offers a job (accept-only). Scene: \`AshenveilScene.js\`.\n\n`;
  }

  if (Quests.seraph) {
    md += `## Seraphim road — Dragonspine (Seraphim only)\n\nFlags \`q-sq1\`..\`q-sq4\`. Inn → spine trail east of the grove (treaty stone bars non-seraphs) → Dragonspine → duel the five banners → recruit ONE → Skyreach shrine ascension. Scene: \`MountainScene.js\`.\n\n`;
    md += `| # | id | Title | Objective |\n|---|---|---|---|\n`;
    for (const q of Quests.seraph.main) md += `| ${q.id.match(/sq(\d)/) ? q.id.match(/sq(\d)/)[1] : ''} | \`${q.id}\` | ${esc(q.title)} | ${esc(q.objective)} |\n`;
    md += `\n### The five duel candidates (recruit exactly one)\n\n| id | Name | Map tile [x,y] | Banner | Combat pack |\n|---|---|---|---|---|\n`;
    for (const c of Quests.seraph.candidates) {
      const pack = (c.pack || []).map(e => e.type).join(', ');
      md += `| \`${c.id}\` | ${esc(c.name)} | [${c.spot}] | ${esc((c.banner || [])[0])} | ${pack} |\n`;
    }
    md += `\nRecruit sets flag \`seraph-recruit=<id>\` and \`q-sq3-five-banners=done\`. Win flag per duel: \`duel-<id>=won\`.\n\n`;
  }

  md += `## Guild board — repeatable hunt contracts (all characters)\n\nTurned in at the Karridge guild; progress tracked in \`world.questCounts[id]\`. Pay scales by guild rank (see characters.md). Defined in \`quests.js → guildBoard\`.\n\n`;
  md += `| id | Title | Region | Kills needed | Base reward |\n|---|---|---|---|---|\n`;
  for (const q of Quests.guildBoard) md += `| \`${q.id}\` | ${esc(q.title)} | ${esc(q.region)} | ${q.need} | ${q.copper}c + ${esc(q.potionLabel)} |\n`;
  md += `\n**Guild ranks** (\`quests.js → guildRanks\`): ` + Quests.guildRanks.map(r => `${r.name} (${r.at}+ hunts ×${r.mult})`).join(', ') + `.\n`;
  write('quests.md', md);
})();

/* ---------------- CHARACTERS ---------------- */
(function () {
  let md = head('Characters');
  md += `## Playable champions (4)\n\nKits are a verbatim port of \`the-pit-of-karridge.html\` — **do not rebalance** (see combat.md). Defined across \`pit.js\`.\n\n`;
  md += `| Champion | Progression | Core kit |\n|---|---|---|\n`;
  md += `| Ronin | per-KILL stat growth; katana→nodachi→odachi at STR 20/40 | SLASH (3-hit kendo), HEAVY (overhead), PARRY (deflect+heal+air-slash), ROLL |\n`;
  md += `| Druid | LEVEL 1–10; forms at lv3/lv6 | GLAIVE, VINES, ROLL, FORM (human↔bear↔wolf: claw/roar/howl) |\n`;
  md += `| Warlock | LEVEL 1–10; unlocks lv3/5/8; LICH on death-with-dragon | HEX, SUMMON (hold-channel: fiend/dragon/coven), PORTAL, BLINK; ARCH DEVIL; LICH (scythe/fade) |\n`;
  md += `| Seraphim | LEVEL 1–10; unlocks lv3/6/8; IMMORTAL grace (1/fight) | SPEAR (couched poke), HALO RAY (1s, converts kills to 7s minions), ASCEND, ROLL |\n\n`;

  md += `## Companions (6) — recruitable, fight alongside you\n\nDefined in \`world/companions.js\`. With an Anthropic key in \`config.js\` they gain free-text AI chat (persona = system prompt); without a key they use scripted dialog. \`scriptedOnly:true\` = no dedicated recruit flow.\n\n`;
  md += `| Key | Name | Found in | Recruit gate | Blurb |\n|---|---|---|---|---|\n`;
  for (const [k, c] of Object.entries(Companions))
    md += `| \`${k}\` | ${esc(c.name)} | ${esc(c.where)} (tile [${c.spot}]) | ${c.recruitFlag ? '`' + c.recruitFlag + '`' : (c.scriptedOnly ? 'scripted only' : 'item/quest')} | ${esc(c.blurb)} |\n`;
  md += `\n### Companion personas (AI system prompts)\n\n`;
  for (const [k, c] of Object.entries(Companions)) md += `**${esc(c.name)}** — ${esc(c.persona)}\n\n`;

  md += `## Key NPCs\n\n`;
  md += `- **Marlow** — innkeeper of the Last Lantern, Karridge. Main-quest giver (conspiracy track). Treats the Seraphim with terror-politeness.\n`;
  md += `- **Bellow** — the Pit announcer. Offers 15 silver to leave after fight 3.\n`;
  md += `- **The Veiled Woman / Quarry Boy / Shen Sama** — conspiracy beats 3–4.\n`;
  md += `- **AnkuNyx (the Dragon Emperor)** — finale cameo. (Lore: the Ronin IS him, incognito — Book 4 egg.)\n`;
  md += `- **Cookie** — Varenholm dancer, druid epilogue. **Lady Nyx** — the Matron, warlock epilogue.\n`;
  md += `- **Duel champions** — Kargoth, Skarva, Nibnob, Vesshk, Aurvaeth (see quests.md).\n`;
  write('characters.md', md);
})();

/* ---------------- MONSTERS ---------------- */
const MONSTER_BEHAVIOR = {
  door:   'TANK. Frontal shield blocks normal hits — flank it or break the guard with HEAVY.',
  hook:   'Fast dual skirmisher, hooks/pulls. Usually spawns in pairs.',
  chain:  'Long reach (nine feet); owns the space around it. Close in or get clipped.',
  pyre:   'Fire mage — leaves burning ground zones. Don\'t stand in fire.',
  gunner: 'Ranged "powder saint" — fires from ~40ft. Close the distance or break line of sight.',
  grave:  'Riposte duelist — PARRIES your swing and counters. Bait the parry, then hit, or use ranged.',
  stitch: 'HEALER ("Stitcher") — mends the whole pack. Kill it first or burst past its healing.',
  brute:  'Aggro tank minion (paired with Stitcher). Big shove, low damage.',
  master: 'Hound master — commands a pack of fast hounds.',
  hound:  'Fast lunging minion; travels in packs. Low HP.',
  necro:  'Gravedigger — raises the dead/thralls. Used as the "mage/raiser" wildcard.',
  champ:  'Former champion — eats thrown-in thralls to grow stats mid-fight (fight 19).',
  beast:  'Bellow\'s Secret — final boss; multi-phase, charges (fight 20).',
  skel:   'Reskin base (goblins/skeletons in field packs).',
  thrall: 'Throwaway minion the champ feeds on.',
  zombie: 'Risen by warlock infection / necro; shambler.',
};
(function () {
  let md = head('Monsters');
  md += `## Enemy types (behaviors)\n\nEvery monster in the game is one of these base types (field packs are reskins with different HP/color). Behaviors live in \`pit.js → updEnemy\`. **Curated table — update by hand if you change an AI.**\n\n`;
  md += `| type | Behavior |\n|---|---|\n`;
  for (const [t, b] of Object.entries(MONSTER_BEHAVIOR)) md += `| \`${t}\` | ${esc(b)} |\n`;

  md += `\n## Named bosses\n\nThe boss expansion adds named, banner-titled fights with their own health bars (\`boss:true\`/\`deathCol\`) and a kill cinematic. Each REUSES one of the base AI types above (no bespoke boss engine) and scales on the per-zone HP ladder (forest x2, undead x4, mountain x6 — Dragonspine regulars also hit ~15% harder, item-15 balance; bosses x5). **Curated table — update by hand when bosses change.**\n\n`;
  md += `| Boss | Zone | AI type | Source |\n|---|---|---|---|\n`;
  md += `| Briar, the Green Orphan | Thorn Grove | \`rotwarden\` | Warlock Hunt (wq4) capture |\n`;
  md += `| Ossuary, the Quiet Boy | Root-Hollow dungeon | \`necro\` | Warlock Hunt (wq4) capture |\n`;
  md += `| Cinder, the Ash-Wick | Dragonspine | \`pyre\` | Warlock Hunt (wq4) capture |\n`;
  md += `| Whisper, the Ninth Ward | The Ashenveil | \`collector\` | Warlock Hunt (wq4) capture |\n`;
  md += `| The Thornwarden + Cookie | Varenholm | \`champ\` + \`rotwarden\` | Warlock Hunt (wq4) climax (2 bosses) |\n`;
  md += `| The Cult Warlock | Varenholm | \`collector\` | Druid Crossing (dq) — comes to cage you |\n`;
  md += `| The Cult Warlock (risen) | Varenholm | \`collector\` + 2x \`grave\` | Druid Crossing (dq) — Anku-reinforced rematch |\n`;
  md += `| The Warden of the Unfiled | The Ashenveil undercroft | \`door\` | Lower-Levels raid (g-ashlower) — mid-zone mini-boss; drops the DUELIST'S KNOT relic |\n`;
  md += `| The Thing the Web Saves | The Ashenveil undercroft | \`necro\` | Lower-Levels raid (g-ashlower) — deep-door finale (boss x5); gated behind the Warden |\n`;

  md += `\n## Questline bosses & encounters\n\n`;
  md += `- **The Warlock's Hunt (wq4):** Lady Nyx commissions five live captures, one boss per zone — Briar (Grove), Ossuary (dungeon), Cinder (Dragonspine), Whisper (Ashenveil), and the climax Cookie + the Thornwarden (Varenholm). All proximity/ambush packs are gated so none can proc during the capture dialogues.\n`;
  md += `- **The Druid's Crossing (dq):** the cult warlock attacks the druid at Varenholm (1 boss), gets back up with Anku reinforcements (boss + 2x grave), then the druid flees up the Dragonspine to Shen Sama — a narrative/credits beat about the missing hearth-wyrm Ignis.\n`;
  md += `- **The Ashenveil Lower Levels (g-ashlower):** an optional raid undercroft beneath the dark academy, reached by descending the Academy stairs (sets \`q-ash-raid\`). Feral undead packs (cell ghouls, vault wraiths, unfiled wights) restock every descent; a mid-zone mini-boss — **the Warden of the Unfiled** (\`door\`, undead tier x4) — drops the DUELIST'S KNOT relic and unlocks the sealed **DEEP DOOR**, whose finale boss **the Thing the Web Saves** (\`necro\`, boss x5) is the hardest fight in the undercroft. All triggers are conversation-safe and fail-safe (dialogs auto-advance under AUTO:FULL), and QuestNav routes the whole undercroft so AUTO can clear it headlessly.\n`;

  md += `\n## Arena gauntlet roster (20 fights)\n\nDefined in \`pit.js → FIGHTS\`. After fight 3, every fight also gains a \`stitch\` healer + a random wildcard (door/gunner/necro/pyre) dead-center.\n\n`;
  md += `| # | Name | Record | Enemies |\n|---|---|---|---|\n`;
  FIGHTS.forEach((f, i) => {
    let types = '?'; try { types = f.spawn(1).map(e => e.type).join(', '); } catch (e) {}
    md += `| ${i + 1} | ${esc(f.name)} | ${esc(f.rec)} | ${types} |\n`;
  });

  md += `\n## Field hunt packs by zone\n\nSpawned by each scene's pack list; respawn rules differ (grove = flag-gated until guild turn-in; mountain/ashenveil = restock every visit).\n\n`;
  md += `- **Thorn Grove** (\`GroveScene.js\`): wolves, hounds, rotshaman, goblins, stranglevines, chitterswarm (insects), toll bandits.\n`;
  md += `- **Dragonspine** (\`MountainScene.js\`): goblins, orcs, ogres, slimes, wyverns, fire elementals.\n`;
  md += `- **The Ashenveil** (\`AshenveilScene.js\`): skeletons, zombies, vampires, werewolves, renegade dark mages.\n`;
  md += `- **The Ashenveil undercroft** (\`AshLowerScene.js\`): cell ghouls, vault wraiths, unfiled wights (undead tier x4; restocks every descent).\n`;
  write('monsters.md', md);
})();

/* ---------------- LOCATIONS ---------------- */
(function () {
  let md = head('Locations & travel');
  md += `## Zones\n\n| Zone id | Scene file | Music | Who goes here |\n|---|---|---|---|\n`;
  md += `| \`karridge-city\` | CityScene.js | city.mp3 | all |\n`;
  md += `| \`thorn-grove\` | GroveScene.js | grove.mp3 | all |\n`;
  md += `| \`grove-dungeon\` | DungeonScene.js | dungeon.mp3 | all (Root-Hollow) |\n`;
  md += `| \`dragonspine\` | MountainScene.js | mountain.mp3 | Seraphim main; all for hunts |\n`;
  md += `| \`varenholm\` | VarenholmScene.js | varenholm.mp3 | Druid epilogue |\n`;
  md += `| \`ashenveil\` | AshenveilScene.js | ashenveil.mp3 | Warlock epilogue; all for hunts |\n`;
  md += `| \`pit-of-karridge\` | ArenaScene.js | per-char pit theme | all (the 20-fight gauntlet) |\n\n`;
  md += `Pit themes: ronin=arena.mp3, druid=pit-druid.mp3, warlock=dungeon.mp3 (zero-dark-thirty), seraph=pit-seraph.mp3.\n\n`;
  md += `## Travel graph & waypoints\n\nRouting + AUTO pathing live in \`core/questnav.js\` (\`nextHop\` HOPS table, \`objective()\`). Gates: city north↔grove south; grove east→spine trail (Dragonspine, seraph only); grove SE→dungeon; city guild→coach (Varenholm/Ashenveil).\n\n`;
  if (CityMap && CityMap.gates) md += `Karridge gate tiles: ` + JSON.stringify(CityMap.gates) + `.\n\n`;
  md += `First-visit cinematic (\`WorldScene.introPan\`) pans to each zone's active objective once, recorded in \`world.seenZones\`.\n`;
  write('locations.md', md);
})();

/* ---------------- README ---------------- */
write('README.md', head('Wiki — auto-generated') +
  `Regenerate everything with:\n\n\`\`\`\nnode game/tools/gen_wiki.js\n\`\`\`\n\n` +
  `- [quests.md](quests.md) — main tracks, seraph duels, warlock epilogue, guild contracts, ranks.\n` +
  `- [characters.md](characters.md) — 4 champions, 6 companions (+personas), key NPCs.\n` +
  `- [monsters.md](monsters.md) — enemy behaviors, arena roster, field packs.\n` +
  `- [locations.md](locations.md) — zones, music, travel graph.\n\n` +
  `Source of truth: \`game/src/world/quests.js\`, \`companions.js\`, \`citymap.js\`, \`combat/pit.js\`. If a fact here looks wrong, the generator is out of date — re-run it.\n`);

console.log('wiki regenerated -> docs/knowledge base/wiki/');
