// Freeze exact displayed prose, reuse unchanged clips, budget only changed speech.
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('node:assert/strict');
const A=require('../../test/harness').load(),D=A.DATA;
const before=JSON.parse(fs.readFileSync(path.join(__dirname,'before.json'),'utf8'));
const voice=JSON.parse(fs.readFileSync('tools/voice_casting.json','utf8')).aldric;
assert.equal(voice,'EFtnObJs7ex53VSB3niw');
const rows=[],seen=new Set();
function add(key,text){if(!text||seen.has(text))return;seen.add(text);rows.push({key:'endcard_'+key.toLowerCase(),text});}
function walk(value,keys=[]){if(typeof value==='string')add(keys.join('_'),value);else for(const [key,child]of Object.entries(value))walk(child,keys.concat(key));}
walk(D.CAMPAIGN3_EPILOGUE);
for(const [id,e]of Object.entries(D.CAMPAIGN3_ENDINGS))add('heading_'+id,e.title+'. '+e.line);
const legacyText=[...new Set([...(before.voice.legacyText||[]),...before.voice.entries.map(row=>row.text)])];
const data={speaker:'aldric',revision:'20260916-epilogue-v2',legacyText,entries:rows};
fs.writeFileSync('js/data/gate_epilogue_voice.js',`// Reviewed Tesfaye end-card narration. Generated by tools/gate_epilogue_review/prepare.js.\n(function(){\n'use strict';\nconst D=ADV.DATA;\nD.GATE_EPILOGUE_VO=${JSON.stringify(data,null,2)};\nfor(const row of D.GATE_EPILOGUE_VO.entries)D.CAMPAIGN3_DIALOGUE.gate.aldric[row.key]=[{t:row.text}];\n})();\n`);
const changed=rows.filter(row=>!before.voice.entries.some(old=>old.key===row.key&&old.text===row.text));
const entries=changed.map(row=>{
 const text='[gentle] '+row.text,hash=crypto.createHash('sha256').update(JSON.stringify([voice,'eleven_v3',text])).digest('hex');
 return{path:`audio/vo/campaign/aldric/${row.key}_1.mp3`,speaker:'aldric',key:row.key,index:1,shown:row.text,text,voice,characters:[...text].length,hash};
});
const characters=entries.reduce((sum,e)=>sum+e.characters,0);
assert.ok(characters+500<=14000,'Review enlarged voice budget');
fs.writeFileSync(path.join(__dirname,'patch.json'),JSON.stringify({model:'eleven_v3',creditCeiling:14000,reserve:500,entries,needsCasting:[]},null,2)+'\n');
console.log(JSON.stringify({totalVariants:rows.length,changedClips:entries.length,reusedClips:rows.length-entries.length,characters,maximumWithReserve:characters+500,voice}));
