'use strict';
const assert=require('assert/strict'),h=require('./harness'),A=h.load();
A.Save.setBackend(h.memBackend());
const g=A.Game.newGame({seed:127,name:'Lifecycle',sex:'f',personalityId:'F01'}),p=A.Game.player(g);
p.inventory.gold=2000;
const base=g.board.find(q=>q.track==='solo');
assert(base,'fixture has a solo contract');
const before=JSON.stringify(A.Save.capture(g));
assert.equal(A.Game.startQuest(g,{...base,track:'party'},{vaultGold:100}).ok,false);
assert.equal(JSON.stringify(A.Save.capture(g)),before,'rejected departure must not charge or move gold');
assert(A.Game.startQuest(g,base).ok);
g.quest.encIdx=base.encounters.length;g.quest.readyToComplete=true;
const outcome=A.Game.completeQuest(g),completed=JSON.stringify(A.Save.capture(g));
assert.strictEqual(A.Game.completeQuest(g),outcome);
assert.equal(JSON.stringify(A.Save.capture(g)),completed,'duplicate completion cannot pay or tick twice');
assert.deepEqual(A.CampaignRoutes.ids(),['original','factions','gate']);
assert.equal(A.CampaignRoutes.forQuest({campaign3:true}).id,'gate');
assert.equal(A.CampaignRoutes.forQuest({campaign2:true}).id,'factions');
assert.equal(A.CampaignRoutes.forQuest({campaign:true}).id,'original');
assert.throws(()=>A.CampaignRoutes.register('gate',{}),/Duplicate/);
console.log('Quest lifecycle: rejected departure, once-only completion and provider selection passed.');
